// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-artworks.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.94.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-artworks.ts
var list_artworks_default = defineTool({
  name: "list_artworks",
  title: "List artworks",
  description: "List artworks in the gallery, optionally filtered by category or availability.",
  inputSchema: {
    category: z.string().trim().optional().describe("Filter by category, e.g. 'painting'."),
    available: z.boolean().optional().describe("Only artworks available for sale."),
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum number of artworks.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, available, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("artworks").select("*").order("id", { ascending: true }).limit(limit ?? 25);
    if (category) query = query.eq("category", category);
    if (typeof available === "boolean") query = query.eq("available", available);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { artworks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-artwork.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var create_artwork_default = defineTool2({
  name: "create_artwork",
  title: "Create artwork",
  description: "Add a new artwork to the gallery. Requires admin privileges on the signed-in account.",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Artwork title."),
    year: z2.string().trim().optional().describe("Year of creation."),
    medium: z2.string().trim().optional().describe("Medium, e.g. 'Oil on canvas'."),
    size: z2.string().trim().optional().describe("Dimensions, e.g. '100 x 80 cm'."),
    category: z2.string().trim().optional().describe("Category grouping."),
    description: z2.string().trim().optional().describe("Description text."),
    price: z2.string().trim().optional().describe("Price as displayed."),
    available: z2.boolean().optional().describe("Whether the artwork is available for sale."),
    image_src: z2.string().trim().optional().describe("Public image URL.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("artworks").insert(input).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { artwork: data }
    };
  }
});

// src/lib/mcp/tools/update-artwork.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var update_artwork_default = defineTool3({
  name: "update_artwork",
  title: "Update artwork",
  description: "Update fields of an existing artwork. Requires admin privileges on the signed-in account.",
  inputSchema: {
    id: z3.number().int().describe("Artwork id."),
    title: z3.string().trim().min(1).optional(),
    year: z3.string().trim().optional(),
    medium: z3.string().trim().optional(),
    size: z3.string().trim().optional(),
    category: z3.string().trim().optional(),
    description: z3.string().trim().optional(),
    price: z3.string().trim().optional(),
    available: z3.boolean().optional(),
    image_src: z3.string().trim().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id, ...patch }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (Object.keys(patch).length === 0) {
      return { content: [{ type: "text", text: "No fields to update" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("artworks").update(patch).eq("id", id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { artwork: data }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "List projects",
  description: "List portfolio projects with their year, location and description.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).default(25).describe("Maximum number of projects.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("projects").select("*").order("id", { ascending: true }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-messages.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_messages_default = defineTool5({
  name: "list_contact_messages",
  title: "List contact messages",
  description: "List messages sent through the site's contact form. Requires admin privileges on the signed-in account.",
  inputSchema: {
    unread_only: z5.boolean().optional().describe("Only return unread messages."),
    limit: z5.number().int().min(1).max(100).default(25).describe("Maximum number of messages.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contact_messages").select("*").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (unread_only) query = query.eq("is_read", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vboxsrizrjinbcamdmuk";
var mcp_default = defineMcp({
  name: "kassiamarin",
  title: "kassiamarin",
  version: "0.1.0",
  instructions: "Tools for the Kassia Marin studio site. Browse and manage gallery artworks and portfolio projects, and read contact form messages. Write tools and messages require an admin account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_artworks_default, create_artwork_default, update_artwork_default, list_projects_default, list_messages_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
