// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xruaonxhkltqqbfpbxot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhydWFvbnhoa2x0cXFiZnBieG90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MzU4NzgsImV4cCI6MjA2NTIxMTg3OH0.aLMMnQIlFrI1mJHUJoB8eOUKndOeCAoKhg2iyqsFKos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);